Twitty/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Twitty.Models
{
    public class User
    {
        public User()
        {
        }

        public int Id { get; set; }
        public string Username { get; set; }

    }
}

Twitty/Controllers/CommentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Neo4j.Driver;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Twitty.Extensions;
using Twitty.Models;
using Twitty.Session;

namespace Twitty.Controllers
{
    public class CommentController : Controller
    {
        private readonly IDriver _driver;

        public CommentController(IDriver driver)
        {
            _driver = driver;
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(string commentInfo, int postId)
        {
            var userId = HttpContext.Session.GetInt32(TwittySessionKeys.UserId) ?? -1;
            if(HttpContext.Session.IsUsernameEmpty() || userId == -1)
                return RedirectToAction("Login");

            var statementText = new StringBuilder();
            statementText.Append(@$"
                MATCH (user:User), (post:Post) WHERE id(user)= {userId} AND id(post)= {postId}
                CREATE (user)-[x:COMMENTED {{commentInfo: '{commentInfo.Replace("'", "")}', whenCommented: '{DateTime.Now}' }}]->(post)");

            var session = _driver.AsyncSession();
            var result = await session.WriteTransactionAsync(tx => tx.RunAsync(statementText.ToString()));
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> EditComment(string commentInfo, int commentId)
        {
            if(HttpContext.Session.IsUsernameEmpty())
                return RedirectToAction("Login");

            var statementText = new StringBuilder();
            statementText.Append($"MATCH ()-[c]->() where id(c) = ${commentId} set c.commentInfo = '${commentInfo}'");

            var session = _driver.AsyncSession();
            var result = await session.WriteTransactionAsync(tx => tx.RunAsync(statementText.ToString()));
            return RedirectToAction("Inedx", "Home");
        }

        public async Task<IActionResult> DeleteComment(int commentId)
        {
            int userId = HttpContext.Session.GetInt32(TwittySessionKeys.UserId) ?? -1;
            if(HttpContext.Session.IsUsernameEmpty() || userId == -1)
                return RedirectToAction("Login");

            var statementText = new StringBuilder();
            statementText.Append($"MATCH (u)-[com]->() WHERE id(com)={commentId} and id(u)={userId} DELETE com");
           
            var session = this._driver.AsyncSession();
            var result = await session.WriteTransactionAsync(tx => tx.RunAsync(statementText.ToString()));
            return RedirectToAction("Index", "Home");
        }

    }
}

Twitty/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Neo4j.Driver;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Twitty.Extensions;
using Twitty.Models;
using Twitty.Session;

namespace Twitty.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDriver _driver;

        public HomeController(IDriver driver)
        {
            _driver = driver;
        }

        public async Task<IActionResult> Index()
        {            
            if(HttpContext.Session.IsUsernameEmpty())
                return RedirectToAction("Login");

            ViewData["userId"] = HttpContext.Session.GetInt32(TwittySessionKeys.UserId);

            string cypherQuery = @"MATCH (u:User)-[:POSTED]->(p:Post)<-[c:COMMENTED]-(uwc:User) return u, p, c, uwc
                                    UNION
                                    MATCH (u:User)-[:POSTED]->(p:Post) return u, p, null as c, null as uwc";

            IList<Post> postsModal = new List<Post>();
            IResultCursor result;
            IAsyncSession session = _driver.AsyncSession();
            try
            {
                result = await session.RunAsync(cypherQuery);
                var records = await result.ToListAsync();
                records.ForEach(rec =>
                {
                    
                    INode user = rec["u"].As<INode>();
                    INode post = rec["p"].As<INode>();
                    INode userWhoCommented = rec["uwc"].As<INode>();
                    IRelationship comment = rec["c"].As<IRelationship>();

                    Post postAlreadyExists = postsModal.FirstOrDefault(postModel => postModel.Id == post.Id);
                    var index = postsModal.IndexOf(postAlreadyExists);

                    

                    Comment commentForPost = null;
                    if(comment != null)
                    {
                        User userWhoCommentedModal = new User()
                        {
                            Id = (int)userWhoCommented.Id,
                            Username = userWhoCommented.Properties["username"].As<string>()
                        };
                        commentForPost = new Comment()
                        {
                            Id = (int)comment.Id,
                            CommentInfo = comment["commentInfo"].As<string>(),
                            WhenCommented = comment["whenCommented"].As<DateTime>(),
                            UserWhoCommented = userWhoCommentedModal
                        };
                    }

                    if(postAlreadyExists != null)
                    {
                        if(commentForPost != null)
                        {
                            postsModal[index].Comments.Add(commentForPost);
                        }
                    }
                    else
                    {
                        User userModel = new User()
                        {
                            Id = (int)user.Id,
                            Username = user.Properties["username"].As<string>(),
                        };
                        Post postModel = new Post()
                        {
                            Id = (int)post.Id,
                            Text = post.Properties["text"].As<string>(),
                            CreationDate = post.Properties["creationDate"].As<DateTime>(),
                            MyUser = userModel,
                        };

                        if(commentForPost != null)
                        {
                            postModel.Comments.Add(commentForPost);
                        }

                        postsModal.Add(postModel);
                    }
                });
            }
            finally
            {
                await session.CloseAsync();
            }


            return View(postsModal.OrderByDescending(post => post.CreationDate).ToList());
        }

        public async Task<IActionResult> Followers()
        {
            int userId = HttpContext.Session.GetInt32(TwittySessionKeys.UserId) ?? -1;
            if(HttpContext.Session.IsUsernameEmpty() || userId == -1)
                    return RedirectToAction("Login");

            ViewData["userId"] = HttpContext.Session.GetInt32(TwittySessionKeys.UserId);

            string cypherQuery = $@"MATCH (mu:User)-[:FOLLOW]->(u:User)-[:POSTED]->(p:Post)<-[c:COMMENTED]-(uwc:User)
                                        where id(mu)={userId} return u, p, c, uwc
                                    UNION
                                    MATCH (mu:User)-[:FOLLOW]->(u:User)-[:POSTED]->(p:Post) 
                                        where id(mu)={userId} return u, p, null as c, null as uwc";

            IList<Post> postsModal = new List<Post>();
            IResultCursor result;
            IAsyncSession session = _driver.AsyncSession();
            try
            {
                result = await session.RunAsync(cypherQuery);
                var records = await result.ToListAsync();
                records.ForEach(rec =>
                {
                    
                    INode user = rec["u"].As<INode>();
                    INode post = rec["p"].As<INode>();
                    INode userWhoCommented = rec["uwc"].As<INode>();
                    IRelationship comment = rec["c"].As<IRelationship>();

                    Post postAlreadyExists = postsModal.FirstOrDefault(postModel => postModel.Id == post.Id);
                    var index = postsModal.IndexOf(postAlreadyExists);

                    

                    Comment commentForPost = null;
                    if(comment != null)
                    {
                        User userWhoCommentedModal = new User()
                        {
                            Id = (int)userWhoCommented.Id,
                            Username = userWhoCommented.Properties["username"].As<string>()
                        };
                        commentForPost = new Comment()
                        {
                            Id = (int)comment.Id,
                            CommentInfo = comment["commentInfo"].As<string>(),
                            WhenCommented = comment["whenCommented"].As<DateTime>(),
                            UserWhoCommented = userWhoCommentedModal
                        };
                    }

                    if(postAlreadyExists != null)
                    {
                        if(commentForPost != null)
                        {
                            postsModal[index].Comments.Add(commentForPost);
                        }
                    }
                    else
                    {
                        User userModel = new User()
                        {
                            Id = (int)user.Id,
                            Username = user.Properties["username"].As<string>(),
                        };
                        Post postModel = new Post()
                        {
                            Id = (int)post.Id,
                            Text = post.Properties["text"].As<string>(),
                            CreationDate = post.Properties["creationDate"].As<DateTime>(),
                            MyUser = userModel,
                        };

                        if(commentForPost != null)
                        {
                            postModel.Comments.Add(commentForPost);
                        }

                        postsModal.Add(postModel);
                    }
                });
            }
            finally
            {
                await session.CloseAsync();
            }


            return View(postsModal.OrderByDescending(post => post.CreationDate).ToList());
        }

        public async Task<IActionResult> UserAsync(int userId)
        {
            var currentUserId = HttpContext.Session.GetInt32(Session.TwittySessionKeys.UserId);
            if(currentUserId == -1 || HttpContext.Session.IsUsernameEmpty())
                return RedirectToAction("Login");

            ViewData["userId"] = HttpContext.Session.GetInt32(TwittySessionKeys.UserId);

            string cypherQuery = $@"MATCH (u)-[:POSTED]->(p:Post)<-[c:COMMENTED]-(uwc:User) where id(u)={userId} return u, p, c, uwc
                                    UNION
                                    MATCH (u)-[:POSTED]->(p:Post) where id(u)={userId} return u, p, null as c, null as uwc";


            IList<Post> postsModal = new List<Post>();
            ViewData["displayFollow"] = null;
            IResultCursor result;
            IAsyncSession session = _driver.AsyncSession();
            try
            {
                result = await session.RunAsync(cypherQuery);
                var records = await result.ToListAsync();
                records.ForEach(rec =>
                {
                    
                    INode user = rec["u"].As<INode>();
                    INode post = rec["p"].As<INode>();
                    INode userWhoCommented = rec["uwc"].As<INode>();
                    IRelationship comment = rec["c"].As<IRelationship>();

                    Post postAlreadyExists = postsModal.FirstOrDefault(postModel => postModel.Id == post.Id);
                    var index = postsModal.IndexOf(postAlreadyExists);

                    

                    Comment commentForPost = null;
                    if(comment != null)
                    {
                        User userWhoCommentedModal = new User()
                        {
                            Id = (int)userWhoCommented.Id,
                            Username = userWhoCommented.Properties["username"].As<string>()
                        };
                        commentForPost = new Comment()
                        {
                            Id = (int)comment.Id,

Twitty/Controllers/PostController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Neo4j.Driver;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Twitty.Extensions;
using Twitty.Models;
using Twitty.Session;
using Post = Twitty.Models.Post;

namespace Twitty.Controllers
{
    namespace Twitty.Controllers
    {
        public class PostController : Controller
        {
            private readonly IDriver _driver;

            public PostController(IDriver driver)
            {
                _driver = driver;
            }      

            [HttpPost]
            public async Task<IActionResult> AddPost(string text)
            {
                string username = HttpContext.Session.GetString(TwittySessionKeys.Username);
                int userId = HttpContext.Session.GetInt32(TwittySessionKeys.UserId) ?? -1;
                if (string.IsNullOrEmpty(username) || userId == -1)
                    return RedirectToAction("Login");   


                var statementText = new StringBuilder();
                statementText.Append(@$"MATCH (u: User) where id(u) = {userId}
                                        CREATE (u)-[:POSTED]->(post:Post {{text: '{text.Replace("'", "")}', creationDate: '{DateTime.Now}'}})");

                var session = _driver.AsyncSession();
                var result = await session.WriteTransactionAsync(tx => tx.RunAsync(statementText.ToString()));

                return RedirectToAction("Index", "Home");
            }
        }
    }
}

Twitty/Views/Home/AddPost.cshtml
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

Twitty/Views/Home/Followers.cshtml
@model IList<Twitty.Models.Post>
@{
    ViewData["Title"] = "Followers Page";

    int? myUserId = (int?)ViewData["userId"];
}

    <div class="container d-flex flex-column" style="justify-content: center;">
        @foreach (var post in Model)
        {
            <div class="card d-flex mb-2" style="width: 75%;">
                <div class="card-body mb-4">
                    <div class="d-flex justify-content-between">
                        <a asp-action="User" asp-route-userId="@post.MyUser.Id" class="card-title"> @post.MyUser.Username </a>
                        <p class="card-text">&nbsp&nbsp @post.CreationDate.ToString("dd.MM.yyyy - HH:mm")</p>
                    </div>
                    <p class="card-text">@post.Text</p>
                    <div>
                        <form asp-action="UnfollowUser" asp-controller="User">
                            <input hidden name="userToUnfollowId" value="@post.MyUser.Id" />
                            <button class="btn btn-block btn-secondary" type="submit">Unfollow me</button>
                        </form>
                        <button class="btn btn-block"
                                data-toggle="collapse"
                                data-target="#comment-@post.Id">
                            Comments
                        </button>
                        <div id="comment-@post.Id" class="collapse">
                            @foreach (var comment in post.Comments)
                            {
                                <div class="row mt-2 border-bottom">
                                    <div class="col-2">
                                        <p class="font-weight-bold">@comment.UserWhoCommented.Username: </p>
                                        @if (myUserId.HasValue && myUserId.Value == comment.UserWhoCommented.Id)
                                        {
                                            <form asp-action="DeleteComment" asp-controller="Comment">
                                                <input type="hidden" name="commentId" value="@comment.Id" />
                                                <button type="submit" class="trash-can btn btn-danger btn-block">Del</button>
                                            </form>
                                        }
                                    </div>
                                    <p class="lead col-8">@comment.CommentInfo</p>
                                    <p class="col-2 align-self-end">@comment.WhenCommented.ToString("dd.MM.yyyy - HH:mm")</p>
                                    <br />
                                </div>

                            }
                            <form asp-action="AddComment" asp-controller="Comment">
                                <input hidden name="postId" value="@post.Id" />
                                <input class="mt-2 mb-2 form-control" placeholder="comment" name="commentInfo" />
                                <button class="btn btn-dark btn-block">Comment</button>
                            </form>

                        </div>
                    </div>

                </div>
            </div>
        }
    </div>
</div>

Twitty/Views/Home/Index.cshtml
@model IList<Twitty.Models.Post>
@{
    ViewData["Title"] = "Home Page";
    
    int? myUserId = (int?)ViewData["userId"];
}

<div class="container">
    <h1>Home page</h1>
    
    <a class="mt-2 mb-2 nav-link text-dark" data-toggle="modal"
       data-target="#exampleModal">Add New Post</a>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <form asp-action="AddPost" asp-controller="Post">
                        <input class="mb-2 form-control" name="text" />
                        <button type="submit" class="btn-block btn btn-dark">Submit post</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="container d-flex flex-column" style="justify-content: center;">
        @foreach (var post in Model)
        {
            <div class="card d-flex mb-2" style="width: 75%;">
                <div class="card-body mb-4">
                    <div class="d-flex justify-content-between">
                        <a asp-action="User" asp-route-userId="@post.MyUser.Id" class="card-title"> @post.MyUser.Username </a>
                        <p class="card-text">&nbsp&nbsp @post.CreationDate.ToString("dd.MM.yyyy - HH:mm")</p>
                    </div>
                    <p class="card-text">@post.Text</p>
                    <div class="">
                        <div style="width: 100%;">
                            <button class="btn btn-block" 
                                    data-toggle="collapse"
                                    data-target="#comment-@post.Id">Comments</button>
                        </div>
                        <div id="comment-@post.Id" class="collapse">
                            @foreach (var comment in post.Comments)
                             {
                                <div class="row mt-2 border-bottom">
                                    <div class="col-2">
                                        <p class="font-weight-bold">@comment.UserWhoCommented.Username: </p>
                                        @if (myUserId.HasValue && myUserId.Value == comment.UserWhoCommented.Id)
                                        {
                                            <form asp-action="DeleteComment" asp-controller="Comment">
                                                <input type="hidden" name="commentId" value="@comment.Id" />
                                                <button type="submit" class="trash-can btn btn-danger btn-block">Del</button>
                                            </form>
                                        }
                                    </div>
                                    <p class="lead col-8">@comment.CommentInfo</p>
                                    <p class="col-2 align-self-end">@comment.WhenCommented.ToString("dd.MM.yyyy - HH:mm")</p>
                                    <br />
                                </div>
                                
                             }
                            <form asp-action="AddComment" asp-controller="Comment" >
                                <input hidden name="postId" value="@post.Id"/>
                                <input class="mt-2 mb-2 form-control" placeholder="comment" name="commentInfo" />
                                <button class="btn btn-dark btn-block">Comment</button>
                            </form>
                            
                        </div>
                    </div>

                </div>
            </div>
        }

    </div>

</div>

Twitty/Views/Home/Login.cshtml
@{
    ViewData["Title"] = "Login page";
}

<div class="container d-flex" style="justify-content: center;">
    <div class="card" style="width: 30rem;">
        <div class="card-body">
            <h5 class="card-title">Login</h5>
            <form method="post" asp-action="Login" asp-controller="User">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="username" name="username" class="form-control" id="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                </div>
                <div class="">
                    <button type="submit" class="btn btn-primary d-flex" style="justify-self: start;">Submit</button>
                    <small class="d-flex" style="justify-self: end;">
                        Don't have an account?&nbsp&nbsp<a asp-controller="Home" asp-action="Register">
                            Register
                            here
                        </a>
                    </small>
                </div>
            </form>
        </div>
    </div>

</div>

Twitty/Views/Home/Register.cshtml
@{
    ViewData["Title"] = "Register page";
}

<div class="container d-flex" style="justify-content: center;">
    <div class="card" style="width: 30rem;">
        <div class="card-body">
            <h5 class="card-title">Register</h5>
            <form asp-action="Register" asp-controller="User">
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" name="email" class="form-control" id="email" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                </div>
                <div class="">
                    <button type="submit" class="btn btn-primary d-flex" style="justify-self: start;">Submit</button>
                </div>
            </form>
        </div>
    </div>

</div>

Twitty/Views/Home/User.cshtml
@model IList<Twitty.Models.Post>
@{
    ViewData["Title"] = "User Page";
    bool? displayFollow = (bool?)ViewData["displayFollow"];
    int? myUserId = (int?)ViewData["userId"];
}

<div class="container">
   @if (displayFollow.HasValue)
    {
    <div class="d-flex justify-content-end">
        @if (displayFollow.Value)
        {
            <form asp-action="FollowUser" asp-controller="User">
                <input hidden name="userToFollowId" value="@Model[0].MyUser.Id" />
                <button class="btn btn-primary" type="submit">Follow me</button>
            </form>
        }
        else
        {
            <form asp-action="UnfollowUser" asp-controller="User">
                <input hidden name="userToUnfollowId" value="@Model[0].MyUser.Id" />
                <button class="btn btn-secondary" type="submit">Unfollow me</button>
            </form>
        }
    </div>
    }

    <div class="container d-flex flex-column" style="justify-content: center;">
        @foreach (var post in Model)
        {
            <div class="card d-flex mb-2" style="width: 75%;">
                <div class="card-body mb-4">
                    <div class="d-flex justify-content-between">
                        <h5 class="card-title"> @post.MyUser.Username </h5>
                        <p class="card-text">&nbsp&nbsp @post.CreationDate.ToString("dd.MM.yyyy - HH:mm")</p>
                    </div>
                    <p class="card-text">@post.Text</p>
                    <div class="">
                        <div style="width: 100%;">
                            <button class="btn btn-block"
                                    data-toggle="collapse"
                                    data-target="#comment-@post.Id">
                                Comments
                            </button>
                        </div>
                        <div id="comment-@post.Id" class="collapse">
                            @foreach (var comment in post.Comments)
                            {
                                <div class="row mt-2 border-bottom">
                                    <div class="col-2">
                                        <p class="font-weight-bold">@comment.UserWhoCommented.Username: </p>
                                        @if (myUserId.HasValue && myUserId.Value == comment.UserWhoCommented.Id)
                                        {
                                            <form asp-action="DeleteComment" asp-controller="Comment">
                                                <input type="hidden" name="commentId" value="@comment.Id" />
                                                <button type="submit" class="trash-can btn btn-danger btn-block">Del</button>
                                            </form>
                                        }
                                    </div>
                                    <p class="lead col-8">@comment.CommentInfo</p>
                                    <p class="col-2 align-self-end">@comment.WhenCommented.ToString("dd.MM.yyyy - HH:mm")</p>
                                    <br />
                                </div>

                            }
                            <form asp-action="AddComment" asp-controller="Comment">
                                <input hidden name="postId" value="@post.Id" />
                                <input class="mt-2 mb-2 form-control" placeholder="comment" name="commentInfo" />
                                <button class="btn btn-dark btn-block">Comment</button>
                            </form>

                        </div>
                    </div>

                </div>
            </div>
        }
    </div>
</div>